using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SmartRecipe.Api.Interfaces;
using SmartRecipe.Api.Models;

namespace SmartRecipe.Api.Services
{
    public class PdfService : IPdfService
    {
        public byte[] GenerateRecipePdf(Recipe recipe)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(1, Unit.Inch);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Header().Text(recipe.Title)
                        .SemiBold().FontSize(24).FontColor(Colors.Blue.Medium);

                    page.Content().PaddingVertical(10).Column(column =>
                    {
                        column.Spacing(10);

                        column.Item().Text("Ingredients").Bold().FontSize(16);
                        column.Item().Text(recipe.Ingredients);

                        column.Item().LineHorizontal(1);

                        column.Item().Text("Instructions").Bold().FontSize(16);
                        column.Item().Text(recipe.Instructions);
                    });

                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by chefAI-Planner");
                    });
                });
            });

            return document.GeneratePdf();
        }
    }
}